WITH RECURSIVE HIERARQUIA AS (
    -- Raiz: todos os nós são considerados ponto de partida
    SELECT
        IOP.IOP_NUM AS INT_NUM_ROOT,
        IOP.INSTALACAO_ID AS MSLINK_ROOT,
        IOP.IOP_NUM AS INT_NUM_TRAFO,
        IOP.INSTALACAO_ID AS MSLINK_TRAFO,
        CAST(IOP.INSTALACAO_ID AS STRING) AS CAMINHO,
        (SELECT COUNT(*) FROM CONSUMIDOR C WHERE C.INSTALACAO_ID = IOP.INSTALACAO_ID) AS TOT_UC,
        0 AS NIVEL
    FROM INSTALACAO_OPERACAO IOP

    UNION ALL

    SELECT
        H.INT_NUM_ROOT,
        H.MSLINK_ROOT,
        IOP.IOP_NUM AS INT_NUM_TRAFO,
        IOP.INSTALACAO_ID AS MSLINK_TRAFO,
        H.CAMINHO || '->' || IOP.INSTALACAO_ID AS CAMINHO,
        (SELECT COUNT(*) FROM CONSUMIDOR C WHERE C.INSTALACAO_ID = IOP.INSTALACAO_ID) AS TOT_UC,
        H.NIVEL + 1
    FROM INSTALACAO_OPERACAO IOP
    JOIN HIERARQUIA H ON IOP.INSTALACAO_CHAVE_PAI_ID = H.MSLINK_TRAFO
    WHERE POSITION(IOP.INSTALACAO_ID IN H.CAMINHO) = 0
)

SELECT *
FROM HIERARQUIA
ORDER BY INT_NUM_ROOT, NIVEL;
