-- Consulta hierárquica em Oracle para contar consumidores por componente da rede

SELECT
    CONNECT_BY_ROOT IOP.IOP_NUM AS INT_NUM_ROOT,
    CONNECT_BY_ROOT IOP.INSTALACAO_ID AS MSLINK_ROOT,
    IOP.IOP_NUM AS INT_NUM_TRAFO,
    IOP.INSTALACAO_ID AS MSLINK_TRAFO,
    (SELECT COUNT(CR_NUMERO)
     FROM CONSUMIDOR C
     WHERE C.INSTALACAO_ID = IOP.INSTALACAO_ID) AS TOT_UC
FROM
    INSTALACAO_OPERACAO IOP
START WITH
    1 = 1 -- Começa de qualquer ponto
CONNECT BY nocycle PRIOR IOP.INSTALACAO_ID = IOP.INSTALACAO_CHAVE_PAI_ID;
